In [405]:
import numpy as np
import plotly as px
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [406]:
df = pd.read_csv('cleaned.csv')

In [407]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Unnamed: 0            4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4803 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  release_date          4802 non-null   object 
 11  revenue               4803 non-null   int64  
 12  runtime               4801 non-null   float64
 13  spoken_languages      4803 non-null   object 
 14  tagline               3959 non-null   object 
 15  vote_average         

In [408]:
df.shape

(4803, 19)

In [409]:
df.dtypes

Unnamed: 0                int64
budget                    int64
genres                   object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
tagline                  object
vote_average            float64
vote_count                int64
cast                     object
crew                     object
dtype: object

In [410]:
df['overview']

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...                        
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: overview, Length: 4803, dtype: object

In [411]:
df['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [412]:
df['overview'].isnull().sum()

3

In [413]:
df['overview'] = df['overview'].fillna('')

In [414]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfv = TfidfVectorizer(min_df=3, max_features=None, ngram_range=(1,3), stop_words = 'english')

In [415]:
tfv_matrix = tfv.fit_transform(df['overview'])

In [416]:
tfv_matrix

<4803x9919 sparse matrix of type '<class 'numpy.float64'>'
	with 121480 stored elements in Compressed Sparse Row format>

In [417]:
tfv_matrix.shape

(4803, 9919)

In [418]:
df['overview'].shape

(4803,)

In [419]:
tfv_matrix.toarray()[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [420]:
tfv_matrix[0].T.toarray()

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [421]:
X = tfv_matrix.toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [422]:
df2 = pd.DataFrame(X)

In [423]:
df2

0     1     2     3     4     5     6     7     8     9     ...  9909  \
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
4798   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4799   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4800   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4801   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4802   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      9910  9911  9912  9913  9914  9915  9916  9917  9918  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
4798   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4799   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4800   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4801   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4802   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[4803 rows x 9919 columns]

In [424]:
from sklearn.metrics.pairwise import sigmoid_kernel

In [425]:
sig = sigmoid_kernel(tfv_matrix, tfv_matrix)

In [426]:
sig

array([[0.76163649, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
        0.76159416],
       [0.76159416, 0.76163649, 0.76159416, ..., 0.76159519, 0.76159416,
        0.76159416],
       [0.76159416, 0.76159416, 0.76163649, ..., 0.76159484, 0.76159416,
        0.76159416],
       ...,
       [0.76159416, 0.76159519, 0.76159484, ..., 0.76163649, 0.76159488,
        0.76159447],
       [0.76159416, 0.76159416, 0.76159416, ..., 0.76159488, 0.76163649,
        0.76159467],
       [0.76159416, 0.76159416, 0.76159416, ..., 0.76159447, 0.76159467,
        0.76163649]])

In [427]:
sig[1]

array([0.76159416, 0.76163649, 0.76159416, ..., 0.76159519, 0.76159416,
       0.76159416])

In [428]:
index = df.index
index

RangeIndex(start=0, stop=4803, step=1)

In [429]:
index

RangeIndex(start=0, stop=4803, step=1)

In [430]:
index[4802]

4802

In [431]:
title = df['original_title']

In [432]:
title[4802]

'My Date with Drew'

In [433]:
indices = pd.Series(df.index, index=df['original_title'])

In [434]:
indices

original_title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ... 
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

In [435]:
indices['Avatar']

0

In [436]:
sig[0]

array([0.76163649, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
       0.76159416])

In [437]:
sig[indices['Avatar']]

array([0.76163649, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
       0.76159416])

In [438]:
list(sig[indices['Avatar']])

[0.7616364930962501,
 0.7615941559557649,
 0.7615941559557649,
 0.761595125164868,
 0.7615941559557649,
 0.761595309447695,
 0.7615941559557649,
 0.761595908255829,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615950846887262,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615957270499999,
 0.7615962614863476,
 0.7615941559557649,
 0.7615952950243241,
 0.7615941559557649,
 0.7615968611459102,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.761597988130195,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615951605621958,
 0.7615941559557649,
 0.7615968356260667,
 0.7615941559557649,
 0.76159560924928

In [439]:
len(list(sig[indices['Avatar']]))

4803

In [440]:
list(enumerate(list(sig[indices['Avatar']])))

[(0, 0.7616364930962501),
 (1, 0.7615941559557649),
 (2, 0.7615941559557649),
 (3, 0.761595125164868),
 (4, 0.7615941559557649),
 (5, 0.761595309447695),
 (6, 0.7615941559557649),
 (7, 0.761595908255829),
 (8, 0.7615941559557649),
 (9, 0.7615941559557649),
 (10, 0.7615941559557649),
 (11, 0.7615950846887262),
 (12, 0.7615941559557649),
 (13, 0.7615941559557649),
 (14, 0.7615941559557649),
 (15, 0.7615941559557649),
 (16, 0.7615941559557649),
 (17, 0.7615941559557649),
 (18, 0.7615941559557649),
 (19, 0.7615941559557649),
 (20, 0.7615941559557649),
 (21, 0.7615941559557649),
 (22, 0.7615941559557649),
 (23, 0.7615941559557649),
 (24, 0.7615941559557649),
 (25, 0.7615941559557649),
 (26, 0.7615957270499999),
 (27, 0.7615962614863476),
 (28, 0.7615941559557649),
 (29, 0.7615952950243241),
 (30, 0.7615941559557649),
 (31, 0.7615968611459102),
 (32, 0.7615941559557649),
 (33, 0.7615941559557649),
 (34, 0.7615941559557649),
 (35, 0.7615941559557649),
 (36, 0.761597988130195),
 (37, 0.7615941

In [441]:
sigma_scores = sorted(
  list(
    enumerate(
      list(
        sig[indices['Avatar']]
      )
    )
  ),
  key = lambda x:x[1], reverse = True
)

In [442]:
sigma_scores

[(0, 0.7616364930962501),
 (1341, 0.7616030155858681),
 (634, 0.7616028561141562),
 (3604, 0.761601930611584),
 (2130, 0.7616015339622925),
 (775, 0.7616011086528326),
 (529, 0.7615996114069044),
 (151, 0.7615991171152051),
 (311, 0.7615990624497703),
 (847, 0.7615987706430225),
 (570, 0.7615986450599548),
 (942, 0.7615984376900236),
 (36, 0.761597988130195),
 (1610, 0.7615979793934843),
 (3070, 0.7615978406764746),
 (1033, 0.7615978182403836),
 (2628, 0.7615977834088159),
 (1784, 0.7615977150705628),
 (2578, 0.7615976778191441),
 (150, 0.7615976453752452),
 (3724, 0.7615975951237102),
 (1013, 0.761597590729192),
 (4211, 0.7615975631290405),
 (1213, 0.7615975380289366),
 (1345, 0.7615974549075267),
 (312, 0.7615974086679765),
 (4039, 0.7615973645677722),
 (2967, 0.7615973512232982),
 (614, 0.7615972949789032),
 (281, 0.7615972537743877),
 (174, 0.7615972462403859),
 (3493, 0.7615971922075141),
 (3624, 0.7615971821325882),
 (972, 0.7615971791001622),
 (1274, 0.7615971587672579),
 (1959,

In [443]:
sigma_scores[1:11]

[(1341, 0.7616030155858681),
 (634, 0.7616028561141562),
 (3604, 0.761601930611584),
 (2130, 0.7616015339622925),
 (775, 0.7616011086528326),
 (529, 0.7615996114069044),
 (151, 0.7615991171152051),
 (311, 0.7615990624497703),
 (847, 0.7615987706430225),
 (570, 0.7615986450599548)]

In [444]:
ind = [index[0] for index in sigma_scores[1:11]]

In [445]:
ind

[1341, 634, 3604, 2130, 775, 529, 151, 311, 847, 570]

In [446]:
df['original_title'].iloc[ind]

1341                Obitaemyy Ostrov
634                       The Matrix
3604                       Apollo 18
2130                    The American
775                        Supernova
529                 Tears of the Sun
151                          Beowulf
311     The Adventures of Pluto Nash
847                         Semi-Pro
570                           Ransom
Name: original_title, dtype: object

In [505]:

"""
CUSTOMIZING FOR MODELS THAT DO NOT INCLUDE THE THING BEING RECOMMENDED FOR
take the product/thing to be recommended
put it through the vectorizer
append to the indicies list
append the new vector to the current model

"""


array([[0.76163649, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
        0.76159416],
       [0.76159416, 0.76163649, 0.76159416, ..., 0.76159519, 0.76159416,
        0.76159416],
       [0.76159416, 0.76159416, 0.76163649, ..., 0.76159484, 0.76159416,
        0.76159416],
       ...,
       [0.76159416, 0.76159519, 0.76159484, ..., 0.76163649, 0.76159488,
        0.76159447],
       [0.76159416, 0.76159416, 0.76159416, ..., 0.76159488, 0.76163649,
        0.76159467],
       [0.76159416, 0.76159416, 0.76159416, ..., 0.76159447, 0.76159467,
        0.76163649]])

In [516]:
indices

original_title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ... 
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

In [518]:
def give_rec(title, model):
  idx = indices[title]
  model_scores = list(enumerate(list(model[idx])))
  model_scores = sorted(model_scores, key = lambda x:x[1], reverse=True )
  model_scores = model_scores[0:11]
  print(model_scores)
  movie_indices = [index[0] for index in model_scores]
  return df['original_title'].iloc[movie_indices]
  

In [519]:
give_rec('Avatar', sig)

[(0, 0.7616364930962501), (1341, 0.7616030155858681), (634, 0.7616028561141562), (3604, 0.761601930611584), (2130, 0.7616015339622925), (775, 0.7616011086528326), (529, 0.7615996114069044), (151, 0.7615991171152051), (311, 0.7615990624497703), (847, 0.7615987706430225), (570, 0.7615986450599548)]


0                             Avatar
1341                Obitaemyy Ostrov
634                       The Matrix
3604                       Apollo 18
2130                    The American
775                        Supernova
529                 Tears of the Sun
151                          Beowulf
311     The Adventures of Pluto Nash
847                         Semi-Pro
570                           Ransom
Name: original_title, dtype: object

In [449]:
df.columns

Index(['Unnamed: 0', 'budget', 'genres', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'release_date', 'revenue', 'runtime', 'spoken_languages', 'tagline',
       'vote_average', 'vote_count', 'cast', 'crew'],
      dtype='object')

In [450]:
df['crew']

0       [{"credit_id": "52fe48009251416c750aca23", "de...
1       [{"credit_id": "52fe4232c3a36847f800b579", "de...
2       [{"credit_id": "54805967c3a36829b5002c41", "de...
3       [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4       [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
                              ...                        
4798    [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4799    [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4800    [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4801    [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4802    [{"credit_id": "58ce021b9251415a390165d9", "de...
Name: crew, Length: 4803, dtype: object

In [451]:
df[0:1]

Unnamed: 0     budget                                             genres  \
0           0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

      id                                           keywords original_language  \
0  19995  [{"id": 1463, "name": "culture clash"}, {"id":...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity                               production_companies release_date  \
0  150.437577  [{"name": "Ingenious Film Partners", "id": 289...   2009-12-10   

      revenue  runtime                                   spoken_languages  \
0  2787965087    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...   

                       tagline  vote_average  vote_count  \
0  Enter the World of Pandora.           7.2       11800   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...

In [452]:
df['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"},

In [453]:
eval(df['crew'][0])

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  

In [454]:
from ast import literal_eval

In [455]:
literal_eval(df['crew'][0])

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  

In [456]:
features = ['cast', 'crew', 'keywords', 'genres']

In [457]:
df['cast']

0       [{"cast_id": 242, "character": "Jake Sully", "...
1       [{"cast_id": 4, "character": "Captain Jack Spa...
2       [{"cast_id": 1, "character": "James Bond", "cr...
3       [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4       [{"cast_id": 5, "character": "John Carter", "c...
                              ...                        
4798    [{"cast_id": 1, "character": "El Mariachi", "c...
4799    [{"cast_id": 1, "character": "Buzzy", "credit_...
4800    [{"cast_id": 8, "character": "Oliver O\u2019To...
4801    [{"cast_id": 3, "character": "Sam", "credit_id...
4802    [{"cast_id": 3, "character": "Herself", "credi...
Name: cast, Length: 4803, dtype: object

In [458]:
for feature in features:
  df[feature] = df[feature].apply(literal_eval)

In [459]:
df.iloc[0]['crew']

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  

In [460]:
df[features]

cast  \
0     [{'cast_id': 242, 'character': 'Jake Sully', '...   
1     [{'cast_id': 4, 'character': 'Captain Jack Spa...   
2     [{'cast_id': 1, 'character': 'James Bond', 'cr...   
3     [{'cast_id': 2, 'character': 'Bruce Wayne / Ba...   
4     [{'cast_id': 5, 'character': 'John Carter', 'c...   
...                                                 ...   
4798  [{'cast_id': 1, 'character': 'El Mariachi', 'c...   
4799  [{'cast_id': 1, 'character': 'Buzzy', 'credit_...   
4800  [{'cast_id': 8, 'character': 'Oliver O’Toole',...   
4801  [{'cast_id': 3, 'character': 'Sam', 'credit_id...   
4802  [{'cast_id': 3, 'character': 'Herself', 'credi...   

                                                   crew  \
0     [{'credit_id': '52fe48009251416c750aca23', 'de...   
1     [{'credit_id': '52fe4232c3a36847f800b579', 'de...   
2     [{'credit_id': '54805967c3a36829b5002c41', 'de...   
3     [{'credit_id': '52fe4781c3a36847f81398c3', 'de...   
4     [{'credit_id': '52fe479ac3a36847f813eaa3', 'de...   
...                                                 ...   
4798  [{'credit_id': '52fe44eec3a36847f80b280b', 'de...   
4799  [{'credit_id': '52fe487dc3a368484e0fb013', 'de...   
4800  [{'credit_id': '52fe4df3c3a36847f8275ecf', 'de...   
4801  [{'credit_id': '52fe4ad9c3a368484e16a36b', 'de...   
4802  [{'credit_id': '58ce021b9251415a390165d9', 'de...   

                                               keywords  \
0     [{'id': 1463, 'name': 'culture clash'}, {'id':...   
1     [{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...   
2     [{'id': 470, 'name': 'spy'}, {'id': 818, 'name...   
3     [{'id': 849, 'name': 'dc comics'}, {'id': 853,...   
4     [{'id': 818, 'name': 'based on novel'}, {'id':...   
...                                                 ...   
4798  [{'id': 5616, 'name': 'united states–mexico ba...   
4799                                                 []   
4800  [{'id': 248, 'name': 'date'}, {'id': 699, 'nam...   
4801                                                 []   
4802  [{'id': 1523, 'name': 'obsession'}, {'id': 224...   

                                                 genres  
0     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...  
1     [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...  
2     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...  
3     [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...  
4     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...  
...                                                 ...  
4798  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...  
4799  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...  
4800  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...  
4801                                                 []  
4802                [{'id': 99, 'name': 'Documentary'}]  

[4803 rows x 4 columns]

In [461]:
'shan '.strip()

'shan'

In [462]:
def get_director(x):
  for i in x:
    if i['job'] == 'Director':
      return i['name'].strip()
  else:
    return np.nan

In [463]:
get_director(df['crew'][0])
# df['crew'][0]

'James Cameron'

In [464]:
df['director'] = df['crew'].apply(get_director)

In [465]:
df['director'].shape

(4803,)

In [466]:
df['director'].isnull().sum()
# df['director'] = df['director'].isnull().fillna('')

30

In [467]:
type(df['cast'][0])

list

In [468]:
'Shan signh '.strip().lower()

'shan signh'

In [469]:
def get_list(x):
  names=[i['name'].strip().lower() for i in x if type(x) == list]
  
  if len(names) > 3:
    return names[0:3]
  else:
    return names
    # return list(set(names))

In [470]:
get_list(df['crew'][0])

['stephen e. rivkin', 'rick carter', 'christopher boyes']

In [471]:
df3 = df.copy()

In [472]:
for feature in features:
  df[feature] = df[feature].apply(get_list)

In [473]:
df[features]

cast  \
0      [sam worthington, zoe saldana, sigourney weaver]   
1         [johnny depp, orlando bloom, keira knightley]   
2          [daniel craig, christoph waltz, léa seydoux]   
3          [christian bale, michael caine, gary oldman]   
4        [taylor kitsch, lynn collins, samantha morton]   
...                                                 ...   
4798  [carlos gallardo, jaime de hoyos, peter marqua...   
4799       [edward burns, kerry bishé, marsha dietlein]   
4800         [eric mabius, kristin booth, crystal lowe]   
4801          [daniel henney, eliza coupe, bill paxton]   
4802  [drew barrymore, brian herzlinger, corey feldman]   

                                                   crew  \
0     [stephen e. rivkin, rick carter, christopher b...   
1     [dariusz wolski, gore verbinski, jerry bruckhe...   
2             [thomas newman, sam mendes, anna pinnock]   
3       [hans zimmer, charles roven, christopher nolan]   
4       [andrew stanton, andrew stanton, john lasseter]   
...                                                 ...   
4798  [robert rodriguez, robert rodriguez, robert ro...   
4799         [edward burns, edward burns, edward burns]   
4800       [carla hetland, harvey kahn, adam sliwinski]   
4801                         [daniel hsia, daniel hsia]   
4802  [clark peterson, andrew reimer, brian herzlinger]   

                                        keywords  \
0             [culture clash, future, space war]   
1             [ocean, drug abuse, exotic island]   
2            [spy, based on novel, secret agent]   
3          [dc comics, crime fighter, terrorist]   
4              [based on novel, mars, medallion]   
...                                          ...   
4798  [united states–mexico barrier, legs, arms]   
4799                                          []   
4800      [date, love at first sight, narration]   
4801                                          []   
4802               [obsession, camcorder, crush]   

                                    genres  
0             [action, adventure, fantasy]  
1             [adventure, fantasy, action]  
2               [action, adventure, crime]  
3                   [action, crime, drama]  
4     [action, adventure, science fiction]  
...                                    ...  
4798             [action, crime, thriller]  
4799                     [comedy, romance]  
4800              [comedy, drama, romance]  
4801                                    []  
4802                         [documentary]  

[4803 rows x 4 columns]

In [474]:
df3[features]

cast  \
0     [{'cast_id': 242, 'character': 'Jake Sully', '...   
1     [{'cast_id': 4, 'character': 'Captain Jack Spa...   
2     [{'cast_id': 1, 'character': 'James Bond', 'cr...   
3     [{'cast_id': 2, 'character': 'Bruce Wayne / Ba...   
4     [{'cast_id': 5, 'character': 'John Carter', 'c...   
...                                                 ...   
4798  [{'cast_id': 1, 'character': 'El Mariachi', 'c...   
4799  [{'cast_id': 1, 'character': 'Buzzy', 'credit_...   
4800  [{'cast_id': 8, 'character': 'Oliver O’Toole',...   
4801  [{'cast_id': 3, 'character': 'Sam', 'credit_id...   
4802  [{'cast_id': 3, 'character': 'Herself', 'credi...   

                                                   crew  \
0     [{'credit_id': '52fe48009251416c750aca23', 'de...   
1     [{'credit_id': '52fe4232c3a36847f800b579', 'de...   
2     [{'credit_id': '54805967c3a36829b5002c41', 'de...   
3     [{'credit_id': '52fe4781c3a36847f81398c3', 'de...   
4     [{'credit_id': '52fe479ac3a36847f813eaa3', 'de...   
...                                                 ...   
4798  [{'credit_id': '52fe44eec3a36847f80b280b', 'de...   
4799  [{'credit_id': '52fe487dc3a368484e0fb013', 'de...   
4800  [{'credit_id': '52fe4df3c3a36847f8275ecf', 'de...   
4801  [{'credit_id': '52fe4ad9c3a368484e16a36b', 'de...   
4802  [{'credit_id': '58ce021b9251415a390165d9', 'de...   

                                               keywords  \
0     [{'id': 1463, 'name': 'culture clash'}, {'id':...   
1     [{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...   
2     [{'id': 470, 'name': 'spy'}, {'id': 818, 'name...   
3     [{'id': 849, 'name': 'dc comics'}, {'id': 853,...   
4     [{'id': 818, 'name': 'based on novel'}, {'id':...   
...                                                 ...   
4798  [{'id': 5616, 'name': 'united states–mexico ba...   
4799                                                 []   
4800  [{'id': 248, 'name': 'date'}, {'id': 699, 'nam...   
4801                                                 []   
4802  [{'id': 1523, 'name': 'obsession'}, {'id': 224...   

                                                 genres  
0     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...  
1     [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...  
2     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...  
3     [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...  
4     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...  
...                                                 ...  
4798  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...  
4799  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...  
4800  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...  
4801                                                 []  
4802                [{'id': 99, 'name': 'Documentary'}]  

[4803 rows x 4 columns]

In [475]:
df.dropna(subset=['director'], inplace=True)

In [476]:
df.isnull().sum()

Unnamed: 0                0
budget                    0
genres                    0
id                        0
keywords                  0
original_language         0
original_title            0
overview                  0
popularity                0
production_companies      0
release_date              0
revenue                   0
runtime                   2
spoken_languages          0
tagline                 822
vote_average              0
vote_count                0
cast                      0
crew                      0
director                  0
dtype: int64

In [477]:
df['cast'][0]

['sam worthington', 'zoe saldana', 'sigourney weaver']

In [478]:
type(df['cast'][0])

list

In [479]:
''.join(df['cast'][0])

'sam worthingtonzoe saldanasigourney weaver'

In [480]:
type(''.join(df['cast'][0]))

str

In [481]:
df[features]

cast  \
0      [sam worthington, zoe saldana, sigourney weaver]   
1         [johnny depp, orlando bloom, keira knightley]   
2          [daniel craig, christoph waltz, léa seydoux]   
3          [christian bale, michael caine, gary oldman]   
4        [taylor kitsch, lynn collins, samantha morton]   
...                                                 ...   
4798  [carlos gallardo, jaime de hoyos, peter marqua...   
4799       [edward burns, kerry bishé, marsha dietlein]   
4800         [eric mabius, kristin booth, crystal lowe]   
4801          [daniel henney, eliza coupe, bill paxton]   
4802  [drew barrymore, brian herzlinger, corey feldman]   

                                                   crew  \
0     [stephen e. rivkin, rick carter, christopher b...   
1     [dariusz wolski, gore verbinski, jerry bruckhe...   
2             [thomas newman, sam mendes, anna pinnock]   
3       [hans zimmer, charles roven, christopher nolan]   
4       [andrew stanton, andrew stanton, john lasseter]   
...                                                 ...   
4798  [robert rodriguez, robert rodriguez, robert ro...   
4799         [edward burns, edward burns, edward burns]   
4800       [carla hetland, harvey kahn, adam sliwinski]   
4801                         [daniel hsia, daniel hsia]   
4802  [clark peterson, andrew reimer, brian herzlinger]   

                                        keywords  \
0             [culture clash, future, space war]   
1             [ocean, drug abuse, exotic island]   
2            [spy, based on novel, secret agent]   
3          [dc comics, crime fighter, terrorist]   
4              [based on novel, mars, medallion]   
...                                          ...   
4798  [united states–mexico barrier, legs, arms]   
4799                                          []   
4800      [date, love at first sight, narration]   
4801                                          []   
4802               [obsession, camcorder, crush]   

                                    genres  
0             [action, adventure, fantasy]  
1             [adventure, fantasy, action]  
2               [action, adventure, crime]  
3                   [action, crime, drama]  
4     [action, adventure, science fiction]  
...                                    ...  
4798             [action, crime, thriller]  
4799                     [comedy, romance]  
4800              [comedy, drama, romance]  
4801                                    []  
4802                         [documentary]  

[4773 rows x 4 columns]

In [482]:
[ ' '.join(crew).replace('.', '') for crew in df['crew'] ][0]

'stephen e rivkin rick carter christopher boyes'

In [483]:
df['crew'][0] 

['stephen e. rivkin', 'rick carter', 'christopher boyes']

In [383]:
df['director'][0]
a = ' '.join(df['cast'][0]) + ' '.join(df['crew'][0]) 
b = ''.join(df['cast'][0]) + '' + ''.join(df['crew'][0]) 
c = ''.join(df['cast'][0]) +' ' + ' '.join(df['crew'][0]) + ' ' + ' '.join(df['keywords'][0]) + ' ' + ' '.join(df['genres'][0]) + ' ' + df['director'][0]


print(a)


sam worthington zoe saldana sigourney weaverstephen e. rivkin rick carter christopher boyes


In [484]:
def create_feature(row):
  crew = ' '.join(row["crew"]).replace('.', '')
  # crew = [ ' '.join(crew).replace('.', '') for crew in df['crew'] ][0]
  return ' '.join(row['keywords']) + ' ' + crew +  ' '.join(row['cast']) + ' ' + row['director'] + ' ' + ' '.join(row['genres'])
  # return ' '.join(row['cast']) + ' ' + ' '.join(row['keywords']) + ' ' + ' '.join(row['genres']) + ' ' + row['director']


In [485]:
df['meta_blob'] = df.apply(create_feature, axis=1)

In [486]:
df['meta_blob'][0]

'culture clash future space war stephen e rivkin rick carter christopher boyessam worthington zoe saldana sigourney weaver James Cameron action adventure fantasy'

In [487]:
df.head(2)

Unnamed: 0     budget                        genres     id  \
0           0  237000000  [action, adventure, fantasy]  19995   
1           1  300000000  [adventure, fantasy, action]    285   

                             keywords original_language  \
0  [culture clash, future, space war]                en   
1  [ocean, drug abuse, exotic island]                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   

                                production_companies  ...     revenue  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...  2787965087   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   961000000   

   runtime                                   spoken_languages  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...   
1    169.0           [{"iso_639_1": "en", "name": "English"}]   

                                          tagline vote_average  vote_count  \
0                     Enter the World of Pandora.          7.2       11800   
1  At the end of the world, the adventure begins.          6.9        4500   

                                               cast  \
0  [sam worthington, zoe saldana, sigourney weaver]   
1     [johnny depp, orlando bloom, keira knightley]   

                                                crew        director  \
0  [stephen e. rivkin, rick carter, christopher b...   James Cameron   
1  [dariusz wolski, gore verbinski, jerry bruckhe...  Gore Verbinski   

                                           meta_blob  
0  culture clash future space war stephen e rivki...  
1  ocean drug abuse exotic island dariusz wolski ...  

[2 rows x 21 columns]

In [488]:
from sklearn.feature_extraction.text import CountVectorizer

In [489]:
count = CountVectorizer(stop_words = 'english')

In [490]:
count_matrix = count.fit_transform(df["meta_blob"])

In [491]:
count_matrix

<4773x16918 sparse matrix of type '<class 'numpy.int64'>'
	with 83503 stored elements in Compressed Sparse Row format>

In [492]:
count_matrix.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [494]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim2 = cosine_similarity(count_matrix, count_matrix)

In [495]:
cosine_sim2

array([[1.        , 0.13093073, 0.08728716, ..., 0.        , 0.        ,
        0.        ],
       [0.13093073, 1.        , 0.08      , ..., 0.        , 0.        ,
        0.        ],
       [0.08728716, 0.08      , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [496]:
cosine_sim2[0]

array([1.        , 0.13093073, 0.08728716, ..., 0.        , 0.        ,
       0.        ])

In [497]:
df['original_title'][6]

'Tangled'

In [520]:
give_rec('Tangled', cosine_sim2)

[(6, 1.0000000000000002), (40, 0.3282439759448873), (1511, 0.3175264481385601), (89, 0.2948839123097943), (566, 0.2909571869813232), (130, 0.2886751345948129), (34, 0.21081851067789198), (1391, 0.21081851067789198), (54, 0.2057377999494559), (124, 0.2057377999494559), (269, 0.2057377999494559)]


6                                 Tangled
40                                 Cars 2
1511    Dreamer: Inspired By a True Story
89                         Wreck-It Ralph
566                                  Cars
130                                  Bolt
34                    Monsters University
1391                       License to Wed
54                      The Good Dinosaur
124                                Frozen
269             The Princess and the Frog
Name: original_title, dtype: object

In [521]:
give_rec('The Godfather', cosine_sim2)

[(3337, 1.0000000000000002), (2731, 0.7722761762522595), (867, 0.7188946323483355), (3401, 0.7146943350099464), (1209, 0.7073170731707317), (1018, 0.6906719869328343), (2600, 0.6829268292682926), (1167, 0.6752110364284797), (4201, 0.6587029695195818), (3012, 0.6090155300940286), (3735, 0.607373393411656)]


3337              The Godfather
2731     The Godfather: Part II
867     The Godfather: Part III
3401                      Twixt
1209              The Rainmaker
1018            The Cotton Club
2600           New York Stories
1167                    Dracula
4209           The Conversation
3012              The Outsiders
3738        Lost in Translation
Name: original_title, dtype: object

In [503]:
give_rec('The Godfather', sig)

3337                                      The Godfather
2731                             The Godfather: Part II
1873                                         Blood Ties
3730                                              Cargo
867                             The Godfather: Part III
3623                                               Made
3963                                 They Came Together
2464                             The Master of Disguise
2973    For Greater Glory - The True Story of Cristiada
2389                                        Renaissance
1475                                  Playing for Keeps
Name: original_title, dtype: object