In [22]:
import pandas as pd
import numpy as np
import seaborn as sns
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors

In [2]:
data = pd.read_csv(r'../data/knn-correlation/clean_data.csv')

In [3]:
data.head(2)

userId  movieId  rating           title                      genres  \
0       1        2     3.5  Jumanji (1995)  Adventure|Children|Fantasy   
1       5        2     3.0  Jumanji (1995)  Adventure|Children|Fantasy   

   TotalRatingCount  
0               112  
1               112

In [16]:
data.shape

(100000, 6)

In [4]:
data['title']

0                   Jumanji (1995)
1                   Jumanji (1995)
2                   Jumanji (1995)
3                   Jumanji (1995)
4                   Jumanji (1995)
                   ...            
99995    He Walked by Night (1948)
99996      Lone Ranger, The (1956)
99997      Gardens of Stone (1987)
99998            Field, The (1990)
99999              Fired Up (2009)
Name: title, Length: 100000, dtype: object

In [5]:
len(set(data['title']))

8225

In [6]:
data.columns

Index(['userId', 'movieId', 'rating', 'title', 'genres', 'TotalRatingCount'], dtype='object')

In [13]:
pivot_table = data.pivot_table(index= 'title', columns='userId', values='rating').fillna(0)

In [14]:
pivot_table

userId                                   1    2    3    4    5    6    7    \
title                                                                        
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'burbs, The (1989)                       0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...                                      ...  ...  ...  ...  ...  ...  ...   
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  0.0  0.0  0.0  0.0   
eXistenZ (1999)                          0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx (2002)                               0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx: State of the Union (2005)           0.0  0.0  0.0  0.0  0.0  0.0  0.0   
¡Three Amigos! (1986)                    0.0  0.0  0.0  0.0  0.0  0.0  2.0   

userId                                   8    9    10   ...  693  694  695  \
title                                                   ...                  
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  ...  0.0  0.0  0.0   
'burbs, The (1989)                       0.0  0.0  0.0  ...  0.0  0.0  0.0   
...                                      ...  ...  ...  ...  ...  ...  ...   
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  ...  0.0  0.0  0.0   
eXistenZ (1999)                          0.0  0.0  0.0  ...  0.0  0.0  0.0   
xXx (2002)                               0.0  0.0  0.0  ...  0.0  0.0  0.0   
xXx: State of the Union (2005)           0.0  0.0  0.0  ...  0.0  0.0  0.0   
¡Three Amigos! (1986)                    0.0  0.0  0.0  ...  0.0  4.0  0.0   

userId                                   696  697  698  699  700  701  702  
title                                                                       
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'burbs, The (1989)                       0.0  0.0  0.0  0.0  3.5  0.0  0.0  
...                                      ...  ...  ...  ...  ...  ...  ...  
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
eXistenZ (1999)                          0.0  0.0  0.0  0.0  0.0  0.0  0.0  
xXx (2002)                               0.0  0.0  0.0  0.0  0.0  0.0  0.0  
xXx: State of the Union (2005)           0.0  0.0  0.0  0.0  0.0  0.0  0.0  
¡Three Amigos! (1986)                    3.0  0.0  0.0  0.0  0.0  0.0  0.0  

[8225 rows x 702 columns]

In [15]:
pivot_table.shape

(8225, 702)

In [19]:
pivot_table.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
feature_matrix = csr_matrix(pivot_table.values)

In [21]:
feature_matrix


<8225x702 sparse matrix of type '<class 'numpy.float64'>'
	with 99997 stored elements in Compressed Sparse Row format>

In [23]:
model = NearestNeighbors(metric = 'cosine', algorithm = 'brute')

can you train_test_split here ?

In [25]:
model.fit(feature_matrix)

NearestNeighbors(algorithm='brute', metric='cosine')

In [27]:
pivot_table.shape

(8225, 702)

In [34]:
random_user_index = np.random.choice(pivot_table.shape[1])

In [35]:
random_movie_index = np.random.choice(pivot_table.shape[0])

In [36]:
random_movie_index

996

In [32]:
pivot_table.iloc[random_movie_index]

userId
1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
      ... 
698    0.0
699    0.0
700    0.0
701    0.0
702    0.0
Name: Alaska (1996), Length: 702, dtype: float64

In [39]:
pivot_table.iloc[random_movie_index,:].values.reshape(1, -1)

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 5. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. 

In [42]:
distances, indicies = model.kneighbors(pivot_table.iloc[random_movie_index, :].values.reshape(1, -1), n_neighbors = 8)

In [43]:
distances

array([[0.        , 0.08660509, 0.19651509, 0.21603555, 0.25670585,
        0.25670585, 0.25670585, 0.25670585]])

In [45]:
indicies

array([[ 996, 4120, 5748,   21, 4533,  498, 4162, 5109]])

In [59]:
pivot_table.iloc[random_movie_index].name

'Blood: The Last Vampire (2000)'

In [53]:
pivot_table.iloc[indicies.flatten()].index

Index(['Blood: The Last Vampire (2000)',
       'Kung Fu Panda: Secrets of the Furious Five (2008)',
       'Pokémon: The First Movie (1998)', '102 Dalmatians (2000)',
       'Mac and Me (1988)', 'Arthur and the Invisibles (2007)',
       'Langoliers, The (1995)', 'My Mom's New Boyfriend (2008)'],
      dtype='object', name='title')

In [62]:
pivot_table.iloc[indicies.flatten()].index[1:6]

Index(['Kung Fu Panda: Secrets of the Furious Five (2008)',
       'Pokémon: The First Movie (1998)', '102 Dalmatians (2000)',
       'Mac and Me (1988)', 'Arthur and the Invisibles (2007)'],
      dtype='object', name='title')

In [63]:
distances.flatten()

array([0.        , 0.08660509, 0.19651509, 0.21603555, 0.25670585,
       0.25670585, 0.25670585, 0.25670585])

In [70]:
for i in range(0, len(distances.flatten())):
  if i == 0:
    print('Recommendation for {0}'.format(pivot_table.iloc[random_movie_index].name))
  else:
            print('{} : {} , with a distance of {}'.format(i,pivot_table.index[indicies.flatten()[i]],distances.flatten()[i]))

Recommendation for Blood: The Last Vampire (2000)
1 : Kung Fu Panda: Secrets of the Furious Five (2008) , with a distance of 0.08660509424741969
2 : Pokémon: The First Movie (1998) , with a distance of 0.19651508840734033
3 : 102 Dalmatians (2000) , with a distance of 0.21603554927949697
4 : Mac and Me (1988) , with a distance of 0.2567058537528336
5 : Arthur and the Invisibles (2007) , with a distance of 0.2567058537528336
6 : Langoliers, The (1995) , with a distance of 0.2567058537528336
7 : My Mom's New Boyfriend (2008) , with a distance of 0.2567058537528336
